apiVersion: v1
kind: ConfigMap
metadata:
  namespace: aincrad
  name: spring-boot-envs
data:
  PORT: '58094'
  REDIS_DATABASE: '1'
  REDIS_MASTER: 'pagcloud'
  REDIS_NODES: '10.188.24.193:26379,10.189.25.95:26379,10.189.17.122:26379,10.188.16.158:26379'
  REDIS_TIMEOUT: '10000ms'
  CACHE_TTL: '14400000'
  CUSTOMER_SERVICE_BASE_URL: 'https://customer-service-api.dev.intranet.pagseguro.uol'
  CUSTOMER_SERVICE_GRAPHQL_ENDPOINT: '/graphql'

  SERVER_PORT: '58094'
  SPRING_PROFILES_ACTIVE: 'dev'
  SPRING_CLOUD_CONFIG_PROFILE: 'pagcloud'
  SPRING_CLOUD_CONFIG_LABEL: 'dev'
  SPRING_CLOUD_CONFIG_URI: 'http://salesforce-config-server'
  EUREKA_INSTANCE_HOSTNAME: 'api.customer.onboarding.fdv.servicedesk.k8s.dev.intranet.pags'
  CUSTOMER_SERVICE_ENDPOINT: '/customers'
